apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maven-rules
  title: Maven Rules
  description: >
    Maven enforcer-regler og best practices-oppsett for KS Digital-prosjekter.
  annotations:
    github.com/project-slug: ks-no/maven-rules
    backstage.io/techdocs-ref: dir:.
  tags:
    - maven
    - java
spec:
  type: library
  owner: group:team-utviklerplattform
  lifecycle: production
